### ISSUE TITLE
Add documentation for variable declaration

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/cashscript#10]
[The Language Documentation](https://developer.bitcoin.com/cashscript/docs/language) doesn't mention how to create variables nor anything about how they're scoped.

Add documentation for variables. For example

--

Like in other languages, in CashScript variables contain values. And like many other languages, in CashScript variables are scoped at the block level.

Since the only blocks in CashScript are `function` and `if/else`, variables are relatively basic. There is no keyword for declaring a variable. To declare a variable you start with it's data type then a name followed by an assigned value. Example:

```
string foo = 'bar';
int 3 = 5;
bool notTrue = false;
int abs = abs(3)
int min = min(1, 2)
int max = max(2, 3)
```

**Comment by cgcardona** [comment]
Should we add a `let` keyword for defining variables? It's not immediately obvious that you create variables with no keyword.

**Comment by cgcardona** [comment]
Also add documentation for comments which are `//`

Example: https://github.com/Bitcoin-com/cashscript/blob/master/examples/transfer_with_timeout.cash#L6

**Comment by rkalis** [comment]
Right now I don't really want to add type inference to the language, so I don't want to add a `let` keyword. But I'm open to reconsidering that in the future. I think adding a keyword for constant values might be useful though. I'll add this to a separate ticket.
