### ISSUE TITLE
[Bug] cashc version constant doesn't match package version.

### ISSUE THREAD

**Issue by 2qx** [Bitcoin-com/cashscript#100]
It seems with version 0.6.4 the following constant wasn't bumped.

https://github.com/Bitcoin-com/cashscript/blob/bf7753bbded9027372fef3fa4337af0415d58bcf/packages/cashc/src/index.ts#L5

This causes contracts written specifically for 0.6.4 will error because the version constant in  cashc 0.6.4 doesn't match.

**Comment by rkalis** [comment]
Shite. Thanks for that, I'll bump to 0.6.5 to fix that.

**Comment by rkalis** [comment]
Just published v0.6.5. Tbh I should have an automated script to bump the versions everywhere 😅

**Comment by 2qx** [comment]
:+1:  Thanks so much!!
