### ISSUE TITLE
Add pragma keyword to enable experimental compiler features

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/cashscript#16]
Solidity has a [pragma keyword](https://solidity.readthedocs.io/en/v0.5.11/layout-of-source-files.html#pragmas). Per their docs:

> The pragma keyword is used to enable certain compiler features or checks. 

Example usage

```
pragma cashc ^0.1.0-beta.1
```

**Comment by rkalis** [comment]
This has been added in v0.2.0. Currently it only supports version checks, but can be extended with other functioncality in the future.
