### ISSUE TITLE
Support for OP_RETURN outputs

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/cashscript#17]
Bitcoin Cash offers the ability to write small amounts of metadata to the blockchain with each transaction in a `nulldata` output via an `OP_RETURN` Op Code. Encoding verbs for issue, mint, send and burn in to `nulldata` outputs is how tokens work on BCH for example. Also protocols such as the social network Memo work via encoding data in to `nulldata` outputs w/ `OP_RETURN`

CashScript needs an API for formatting `nulldata` outputs w/ `OP_RETURN`. What should it look like? 

* `buffer opReturn(bytes data)`
* `buffer nullData(bytes opReturn)`

**Comment by rkalis** [comment]
I'll add the option for adding OP_RETURN outputs to the CashScript SDK. This at least allows you to add things like Memo stuff to CashScript outputs. However, it doesn't imply SLP support, as sending tokens to a CashScript contract means they'll likely get burned when using the CashScript SDK. So we will have to better integrate SLP / other OP_RETURN protocols in the future, but this is the first step.

**Comment by rkalis** [comment]
This is included in the latest release `v0.1.2-beta`. I still need to add it to the documentation though.
