### ISSUE TITLE
Editor syntax theme

### ISSUE THREAD

**Issue by rkalis** [Bitcoin-com/cashscript#22]
To improve the developer experience of writing CashScript contracts, we would like to integrate  into VSCode (+ maybe other editors). The good thing is that we are able to leverage a lot of the syntax specification of the [VSCode Solidity syntax theme](https://github.com/juanfranblanco/vscode-solidity), but many of the snippets and other features may be lost on us. It could be beneficial to extend the functionality to include in-editor compilation, linting, etc.

**Comment by rkalis** [comment]
For reference: https://cashscript.org/docs/guides/syntax-highlighting

**Comment by nathanielCherian** [comment]
Hey @rkalis, I've been working on a vscode extension [https://github.com/nathanielCherian/vscode-cashscript](https://github.com/nathanielCherian/vscode-cashscript) (similar to vscode-solidity) that I think is just about ready for release. The features I had planned for the initial release are
- Syntax Highlighting
- Auto-Completion
- Snippets
- Contract Compilation
- Linting (the linting is lexer level linting, still working on getting errors from AST tree)

Is there anything you think needs to be added/changed/removed? Also, I was wondering if you had an SVG version of just the green cashscript triangle-logo?

**Comment by rkalis** [comment]
Wow! This is absolutely amazing, great work man :tada::tada:

I can't think of any other features that I'm missing. Will be sure to try it out and promote it!

**Comment by rkalis** [comment]
Just tried it out and have a few comments on the language syntax. There's a bit too much blue in there, I'd reckon that regular variable names shouldn't be coloured, and arithmetic and other operators should be coloured. Screenshot attached below, contrasted with how it looks when I use Solidity highlighting.

<img width="1103" alt="Screen Shot 2021-06-11 at 08 17 49" src="https://user-images.githubusercontent.com/9142187/121651232-b081c100-ca9a-11eb-81ea-1d6aa193b578.png">
<img width="1103" alt="Screen Shot 2021-06-11 at 09 53 45" src="https://user-images.githubusercontent.com/9142187/121651540-08202c80-ca9b-11eb-874a-65ec7f9327dd.png">

**Comment by nathanielCherian** [comment]
I was having trouble with standardizing the syntax highlighting and I think it's tuned to a specific vscode theme as the contract looks much different on my own machine. I'll tweak with the grammers some more. For testing, what color theme did you use in the screenshot?

**Comment by nathanielCherian** [comment]
I refactored the language grammars and tested them on a minified contract. Here are some renders from different themes:

Monokai dimmed:
![image](https://user-images.githubusercontent.com/55414597/121763454-06815380-caf1-11eb-8b38-3ca9afceb7f9.png)

Monokai:
![image](https://user-images.githubusercontent.com/55414597/121763489-70016200-caf1-11eb-8747-27386371bb67.png)

Dark+:
![image](https://user-images.githubusercontent.com/55414597/121763470-37618880-caf1-11eb-9187-332ce49fbbe5.png)

I'll deploy it in the next patch shortly.

**Comment by rkalis** [comment]
Nice, that looks great!

**Comment by rkalis** [comment]
Just tried it out on my end as well, and it works great! Awesome work! Do you think it's ready for me to tweet about or are there things that you still want to update?

**Comment by nathanielCherian** [comment]
Thanks! I have a couple of very minor updates planned but it may be better to save them for a larger rollout once issues start trickling in. As if right now I think it's ready to share!

**Comment by rkalis** [comment]
Thanks again, really great stuff! Just tweeted about it https://twitter.com/RoscoKalis/status/1404000772413661187?s=20

Also updated the CashScript website https://cashscript.org/docs/guides/syntax-highlighting

**Comment by rkalis** [comment]
Will close this issue now as I think VS Code is the most important editor to have support for.
