### ISSUE TITLE
Improved error messages

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/cashscript#5]
Currently when you name a constructor and function argument the same it gives you a decent error message

```
contract Example(string foo) {
  function compare(string foo) {
    require(foo == foo);
  }
}
```

Gives the error `UnhandledPromiseRejectionWarning: VariableRedefinitionError: Redefinition of variable foo at Line 2, Column 19` which correctly takes you to the first arg of `compare`.

However when you create a correct contract like this:

```
contract Example(string foo) {
  function compare(string bar) {
    require(foo == bar);
  }
}
```

But then instantiate it w/ out an arg

```
  const instance: Instance = contract.new()
```

It gives you `UnhandledPromiseRejectionWarning: Error` which is vague.

**Comment by rkalis** [comment]
This is included in the new release `v0.1.2-beta`.
