### ISSUE TITLE
cashc-cli improvements

### ISSUE THREAD

**Issue by dagurval** [Bitcoin-com/cashscript#55]
It's common *nix convention that if output file argument value is `-`, that the output sent to `stdout` rather than the actual file `-`. Currently cashc creates the file `-`.

For example `wget -O - bitcoin.com` outputs the html to stdout.

This would be useful for testing (`cashc -o - script.cash | less`), or for piping the artifact to other scripts

**Comment by rkalis** [comment]
Other options I want to add before releasing the next version:

- `--hex|-h`: Output compiled bytecode as hex
- `--asm|-s`: Output compiled assembly without artifact data

Another feature that can be useful when combined with these flags:
- `--args|-a [args]`: Include a list of constructor arguments that are automatically prepended to the generated bytecode. Can only be used in combination with `--asm` or `--hex`.

**Comment by rkalis** [comment]
This is released in v0.3.2
